spring.application.name=BluedocsApplication
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/bluedocs
spring.datasource.username=root
spring.datasource.password=Samuel080786
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

